---
- name: Install and configure httpd
  hosts: nodes
  remote_user: ansible
  become: yes
  
  tasks:
  - name: Install httpd
    package:
      name: httpd
      state: present
  - name: Check service state
    service:
      name: httpd
      state: started
  - name: Create index.html
    copy:
      content: "Welcome to my web server"
      dest: /var/www/html/index.html
  - name: Configure firewalld open port 80
    firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled
